version: '3'

services:
    front:
        build: Aplicacao/0 - Apresentacao
        container_name: bpc_bolao_front
        ports:
            - "1994:4200"
        networks:
            - nginx-proxy
        restart: always
    
    mongodbc:
        image: mongo:latest
        container_name: bpc_bolao_db
        ports:
            - "27017:27017"
        networks: 
            - backendapi
        volumes:
            - db_mongo:/data/db
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: lennonalvesdias
            MONGO_INITDB_ROOT_PASSWORD: 08TFYGCHKZ85Q3XQO0YQ684RMFJ7L9FC
    
    apiserver:
        build: .
        container_name: bpc_bolao_api
        ports:
            - "58202:58202"
        networks: 
            - backendapi
            - nginx-proxy
        restart: always

volumes:
    db_mongo:

networks:
    nginx-proxy:
        external: true
    backendapi: